name: hekaya
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  carousel_slider: ^4.2.1
  cloud_firestore: ^4.17.4
  firebase_auth: ^4.19.6
  flutter:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  intl: ^0.19.0
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
#assets folder 
  assets:
    - assets/img/
    - assets/fonts/
    - assets/img/1.jpg
    - assets/img/2.jpg
    - assets/img/3.jpg
    - assets/img/4.jpg
    - assets/img/5.jpg
    - assets/img/6.jpg
    - assets/img/7.jpg
    - assets/img/10.jpg
    - assets/img/11.jpg
    - assets/img/12.jpg
    - assets/img/b2.jpg
    - assets/img/b3.jpg
    - assets/img/b4.jpg
    - assets/img/b5.jpg
    - assets/img/b6.jpg
    - assets/img/g1.png
    - assets/img/h1.jpg
    - assets/img/h2.jpg
    - assets/img/h3.jpg
    - assets/img/ob1.png
    - assets/img/ob2.png
    - assets/img/ob3.png
  fonts:
    - family: SF Pro Text
      fonts:
        - asset: assets/fonts/SF-Pro-Text-Black.otf
        - asset: assets/fonts/SF-Pro-Text-Bold.otf
        - asset: assets/fonts/SF-Pro-Text-Heavy.otf
        - asset: assets/fonts/SF-Pro-Text-Light.otf
        - asset: assets/fonts/SF-Pro-Text-Medium.otf
        - asset: assets/fonts/SF-Pro-Text-Regular.otf
        - asset: assets/fonts/SF-Pro-Text-Semibold.otf
        - asset: assets/fonts/SF-Pro-Text-Thin.otf
        - asset: assets/fonts/SF-Pro-Text-ThinItalic.otf
        - asset: assets/fonts/SF-Pro-Text-Ultralight.otf

